# Generated by Django 5.2.4 on 2025-07-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher_status',
            new_name='teacher_course_status',
        ),
    ]
