# Generated by Django 5.2.4 on 2025-07-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartorderitem_price_course_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='initial_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
